### ISSUE TITLE
ModuleNotFoundError: No module named 'tetranerf'

### ISSUE THREAD

**Issue by kaitolucifer** [jkulhanek/tetra-nerf#11]
```
(pytorch) kaito@Windows:~$ pip install git+https://github.com/jkulhanek/tetra-nerf
...
Building wheels for collected packages: tetra-nerf
  Building wheel for tetra-nerf (setup.py) ... done
  Created wheel for tetra-nerf: filename=tetra_nerf-0.1.1-cp310-cp310-linux_x86_64.whl size=2362 sha256=88e988a7ab02bf204961de7b0790c8f8ce8b321f45f4141233ff239896835e38
  Stored in directory: /tmp/pip-ephem-wheel-cache-qv40epe6/wheels/d5/ce/33/f0d1972d417cc2b2f064573f0a98737d0d0cfc0aba523267e8
Successfully built tetra-nerf
Installing collected packages: tetra-nerf
Successfully installed tetra-nerf-0.1.1
```
tetranerf is installed successfully as shown above.
But when I do `import tetranerf` or use command from nerfstudio like `ns-train tetra-nerf`, it shows like below 
```
(pytorch) kaito@Windows:~$ ns-train tetra-nerf
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/kaito/miniforge3/envs/pytorch/bin/ns-train:5 in <module>                                   │
│                                                                                                  │
│   2 # -*- coding: utf-8 -*-                                                                      │
│   3 import re                                                                                    │
│   4 import sys                                                                                   │
│ ❱ 5 from nerfstudio.scripts.train import entrypoint                                              │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│   8 │   sys.exit(entrypoint())                                                                   │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:62  │
│ in <module>                                                                                      │
│                                                                                                  │
│    59 import yaml                                                                                │
│    60                                                                                            │
│    61 from nerfstudio.configs.config_utils import convert_markup_to_ansi                         │
│ ❱  62 from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion                     │
│    63 from nerfstudio.engine.trainer import TrainerConfig                                        │
│    64 from nerfstudio.utils import comms, profiler                                               │
│    65 from nerfstudio.utils.rich_utils import CONSOLE                                            │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/configs/method_confi │
│ gs.py:626 in <module>                                                                            │
│                                                                                                  │
│   623                                                                                            │
│   624 all_methods, all_descriptions = method_configs, descriptions                               │
│   625 # Add discovered external methods                                                          │
│ ❱ 626 all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_m   │
│   627 all_methods, all_descriptions = sort_methods(all_methods, all_descriptions)                │
│   628                                                                                            │
│   629 # Register all possible external methods which can be installed with Nerfstudio            │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/plugins/registry.py: │
│ 43 in discover_methods                                                                           │
│                                                                                                  │
│   40 │   descriptions = {}                                                                       │
│   41 │   discovered_entry_points = entry_points(group="nerfstudio.method_configs")               │
│   42 │   for name in discovered_entry_points.names:                                              │
│ ❱ 43 │   │   spec = discovered_entry_points[name].load()                                         │
│   44 │   │   if not isinstance(spec, MethodSpecification):                                       │
│   45 │   │   │   CONSOLE.print(                                                                  │
│   46 │   │   │   │   f"[bold yellow]Warning: Could not entry point {spec} as it is not an ins    │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/importlib/metadata/__init__.py:171 in load    │
│                                                                                                  │
│    168 │   │   return the named object.                                                          │
│    169 │   │   """                                                                               │
│    170 │   │   match = self.pattern.match(self.value)                                            │
│ ❱  171 │   │   module = import_module(match.group('module'))                                     │
│    172 │   │   attrs = filter(None, (match.group('attr') or '').split('.'))                      │
│    173 │   │   return functools.reduce(getattr, attrs, module)                                   │
│    174                                                                                           │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/importlib/__init__.py:126 in import_module    │
│                                                                                                  │
│   123 │   │   │   if character != '.':                                                           │
│   124 │   │   │   │   break                                                                      │
│   125 │   │   │   level += 1                                                                     │
│ ❱ 126 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   127                                                                                            │
│   128                                                                                            │
│   129 _RELOADING = {}                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'tetranerf'
```

**Comment by jkulhanek** [comment]
Strange! Can you please post the outputs of `python -c "import tetranerf"' and `whereis ns-train`?

**Comment by kaitolucifer** [comment]
@jkulhanek 
```
(pytorch) kaito@Windows:~$ git clone https://github.com/jkulhanek/tetra-nerf.git
(pytorch) kaito@Windows:~$ cd tetra-nerf/
(pytorch) kaito@Windows:~/tetra-nerf$ pip install -e .
```
And different error pop up.
```
(pytorch) kaito@Windows:~$ cd
(pytorch) kaito@Windows:~$ ns-train tetra-nerf
JAX not installed, skipping Mip-NeRF SSIM
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
TrainerConfig(
    _target=<class 'nerfstudio.engine.trainer.Trainer'>,
    output_dir=PosixPath('outputs'),
    method_name='tetra-nerf',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2023-06-01_214703',
    machine=MachineConfig(seed=42, num_gpus=1, num_machines=1, machine_rank=0, dist_url='auto'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=32768,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=90
    ),
    pipeline=VanillaPipelineConfig(
        _target=<class 'tetranerf.nerfstudio.pipeline.TetrahedraNerfPipeline'>,
        datamanager=VanillaDataManagerConfig(
            _target=<class 'nerfstudio.data.datamanagers.base_datamanager.VanillaDataManager'>,
            data=None,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='off',
                position_noise_std=0.0,
                orientation_noise_std=0.0,
                optimizer=AdamOptimizerConfig(
                    _target=<class 'torch.optim.adam.Adam'>,
                    lr=0.0006,
                    eps=1e-15,
                    max_norm=None,
                    weight_decay=0
                ),
                scheduler=ExponentialDecaySchedulerConfig(
                    _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                    lr_pre_warmup=1e-08,
                    lr_final=None,
                    warmup_steps=0,
                    max_steps=10000,
                    ramp='cosine'
                ),
                param_group='camera_opt'
            ),
            dataparser=MinimalDataParserConfig(
                _target=<class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParser'>,
                data=PosixPath('/home/nikhil/nerfstudio-main/tests/data/lego_test/minimal_parser')
            ),
            train_num_rays_per_batch=4096,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7ff6f8c39480>,
            camera_res_scale_factor=1.0,
            patch_size=1
        ),
        model=TetrahedraNerfConfig(
            _target=<class 'tetranerf.nerfstudio.model.TetrahedraNerf'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=4096,
            tetrahedra_path=None,
            num_tetrahedra_vertices=None,
            num_tetrahedra_cells=None,
            max_intersected_triangles=512,
            num_samples=128,
            num_fine_samples=128,
            use_biased_sampler=True,
            field_dim=64,
            num_color_layers=1,
            num_density_layers=3,
            hidden_size=128,
            input_fourier_frequencies=0,
            initialize_colors=True,
            use_gradient_scaling=True
        )
    ),
    optimizers={
        'fields': {
            'optimizer': RAdamOptimizerConfig(
                _target=<class 'torch.optim.radam.RAdam'>,
                lr=0.001,
                eps=1e-08,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.0001,
                warmup_steps=0,
                max_steps=300000,
                ramp='cosine'
            )
        }
    },
    vis='wandb',
    data=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    steps_per_save=25000,
    steps_per_eval_batch=1000,
    steps_per_eval_image=2000,
    steps_per_eval_all_images=50000,
    max_num_iterations=300000,
    mixed_precision=False,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[21:47:03] Saving config to: outputs/unnamed/tetra-nerf/2023-06-01_214703/config.yml            experiment_config.py:128
           Saving checkpoints to: outputs/unnamed/tetra-nerf/2023-06-01_214703/nerfstudio_models          trainer.py:136
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/kaito/miniforge3/envs/pytorch/bin/ns-train:8 in <module>                                   │
│                                                                                                  │
│   5 from nerfstudio.scripts.train import entrypoint                                              │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(entrypoint())                                                                   │
│   9                                                                                              │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:260 │
│ in entrypoint                                                                                    │
│                                                                                                  │
│   257 │   """Entrypoint for use with pyproject scripts."""                                       │
│   258 │   # Choose a base configuration and override values.                                     │
│   259 │   tyro.extras.set_accent_color("bright_yellow")                                          │
│ ❱ 260 │   main(                                                                                  │
│   261 │   │   tyro.cli(                                                                          │
│   262 │   │   │   AnnotatedBaseConfigUnion,                                                      │
│   263 │   │   │   description=convert_markup_to_ansi(__doc__),                                   │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:246 │
│ in main                                                                                          │
│                                                                                                  │
│   243 │   config.print_to_terminal()                                                             │
│   244 │   config.save_config()                                                                   │
│   245 │                                                                                          │
│ ❱ 246 │   launch(                                                                                │
│   247 │   │   main_func=train_loop,                                                              │
│   248 │   │   num_gpus_per_machine=config.machine.num_gpus,                                      │
│   249 │   │   num_machines=config.machine.num_machines,                                          │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:185 │
│ in launch                                                                                        │
│                                                                                                  │
│   182 │   │   # world_size=0 uses one CPU in one process.                                        │
│   183 │   │   # world_size=1 uses one GPU in one process.                                        │
│   184 │   │   try:                                                                               │
│ ❱ 185 │   │   │   main_func(local_rank=0, world_size=world_size, config=config)                  │
│   186 │   │   except KeyboardInterrupt:                                                          │
│   187 │   │   │   # print the stack trace                                                        │
│   188 │   │   │   CONSOLE.print(traceback.format_exc())                                          │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:99  │
│ in train_loop                                                                                    │
│                                                                                                  │
│    96 │   """                                                                                    │
│    97 │   _set_random_seed(config.machine.seed + global_rank)                                    │
│    98 │   trainer = config.setup(local_rank=local_rank, world_size=world_size)                   │
│ ❱  99 │   trainer.setup()                                                                        │
│   100 │   trainer.train()                                                                        │
│   101                                                                                            │
│   102                                                                                            │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/engine/trainer.py:14 │
│ 9 in setup                                                                                       │
│                                                                                                  │
│   146 │   │   │   │   'test': loads train/test datasets into memory                              │
│   147 │   │   │   │   'inference': does not load any dataset into memory                         │
│   148 │   │   """                                                                                │
│ ❱ 149 │   │   self.pipeline = self.config.pipeline.setup(                                        │
│   150 │   │   │   device=self.device, test_mode=test_mode, world_size=self.world_size, local_r   │
│   151 │   │   )                                                                                  │
│   152 │   │   self.optimizers = self.setup_optimizers()                                          │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/configs/base_config. │
│ py:57 in setup                                                                                   │
│                                                                                                  │
│    54 │                                                                                          │
│    55 │   def setup(self, **kwargs) -> Any:                                                      │
│    56 │   │   """Returns the instantiated object using the config."""                            │
│ ❱  57 │   │   return self._target(self, **kwargs)                                                │
│    58                                                                                            │
│    59                                                                                            │
│    60 # Machine related configs                                                                  │
│                                                                                                  │
│ /home/kaito/tetra-nerf/tetranerf/nerfstudio/pipeline.py:27 in __init__                           │
│                                                                                                  │
│   24 │   │   Pipeline.__init__(self)                                                             │
│   25 │   │   self.config = config                                                                │
│   26 │   │   self.test_mode = test_mode                                                          │
│ ❱ 27 │   │   self.datamanager: VanillaDataManager = config.datamanager.setup(                    │
│   28 │   │   │   device=device,                                                                  │
│   29 │   │   │   test_mode=test_mode,                                                            │
│   30 │   │   │   world_size=world_size,                                                          │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/configs/base_config. │
│ py:57 in setup                                                                                   │
│                                                                                                  │
│    54 │                                                                                          │
│    55 │   def setup(self, **kwargs) -> Any:                                                      │
│    56 │   │   """Returns the instantiated object using the config."""                            │
│ ❱  57 │   │   return self._target(self, **kwargs)                                                │
│    58                                                                                            │
│    59                                                                                            │
│    60 # Machine related configs                                                                  │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/data/datamanagers/ba │
│ se_datamanager.py:384 in __init__                                                                │
│                                                                                                  │
│   381 │   │   │   self.config.data = self.config.dataparser.data                                 │
│   382 │   │   self.dataparser = self.dataparser_config.setup()                                   │
│   383 │   │   self.includes_time = self.dataparser.includes_time                                 │
│ ❱ 384 │   │   self.train_dataparser_outputs = self.dataparser.get_dataparser_outputs(split="tr   │
│   385 │   │                                                                                      │
│   386 │   │   self.train_dataset = self.create_train_dataset()                                   │
│   387 │   │   self.eval_dataset = self.create_eval_dataset()                                     │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/data/dataparsers/bas │
│ e_dataparser.py:163 in get_dataparser_outputs                                                    │
│                                                                                                  │
│   160 │   │   Returns:                                                                           │
│   161 │   │   │   DataparserOutputs containing data for the specified dataset and split          │
│   162 │   │   """                                                                                │
│ ❱ 163 │   │   dataparser_outputs = self._generate_dataparser_outputs(split)                      │
│   164 │   │   return dataparser_outputs                                                          │
│   165                                                                                            │
│   166                                                                                            │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/data/dataparsers/min │
│ imal_dataparser.py:53 in _generate_dataparser_outputs                                            │
│                                                                                                  │
│    50 │                                                                                          │
│    51 │   def _generate_dataparser_outputs(self, split="train"):                                 │
│    52 │   │   filepath = self.config.data / f"{split}.npz"                                       │
│ ❱  53 │   │   data = np.load(filepath, allow_pickle=True)                                        │
│    54 │   │                                                                                      │
│    55 │   │   image_filenames = [filepath.parent / path for path in data["image_filenames"].to   │
│    56 │   │   mask_filenames = None                                                              │
│                                                                                                  │
│ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/numpy/lib/npyio.py:405 in load  │
│                                                                                                  │
│    402 │   │   │   fid = file                                                                    │
│    403 │   │   │   own_fid = False                                                               │
│    404 │   │   else:                                                                             │
│ ❱  405 │   │   │   fid = stack.enter_context(open(os_fspath(file), "rb"))                        │
│    406 │   │   │   own_fid = True                                                                │
│    407 │   │                                                                                     │
│    408 │   │   # Code to distinguish from NumPy binary files and pickles.                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory:
'/home/nikhil/nerfstudio-main/tests/data/lego_test/minimal_parser/train.npz'
```

**Comment by jkulhanek** [comment]
Ok, great, it works.

Now you just need to point it to your data folder. For blender dataset use the blender-data data parser `ns-train tetra-nerf --pipeline.model.tetrahedra-path data/blender/<scene>/pointnerf-0.5.th blender-data --data data/blender/<scene>`. For all other scenes use the minimal-parser data parser `ns-train tetra-nerf --pipeline.model.tetrahedra-path <data folder>/sparse.th minimal-parser --data <data folder>
`.

**Comment by kaitolucifer** [comment]
@jkulhanek 
Ok, thanks.

**Comment by pradeepuNIT** [comment]
> @jkulhanek
> 
> ```
> (pytorch) kaito@Windows:~$ git clone https://github.com/jkulhanek/tetra-nerf.git
> (pytorch) kaito@Windows:~$ cd tetra-nerf/
> (pytorch) kaito@Windows:~/tetra-nerf$ pip install -e .
> ```
> 
> And different error pop up.
> 
> ```
> (pytorch) kaito@Windows:~$ cd
> (pytorch) kaito@Windows:~$ ns-train tetra-nerf
> JAX not installed, skipping Mip-NeRF SSIM
> ──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
> TrainerConfig(
>     _target=<class 'nerfstudio.engine.trainer.Trainer'>,
>     output_dir=PosixPath('outputs'),
>     method_name='tetra-nerf',
>     experiment_name=None,
>     project_name='nerfstudio-project',
>     timestamp='2023-06-01_214703',
>     machine=MachineConfig(seed=42, num_gpus=1, num_machines=1, machine_rank=0, dist_url='auto'),
>     logging=LoggingConfig(
>         relative_log_dir=PosixPath('.'),
>         steps_per_log=10,
>         max_buffer_size=20,
>         local_writer=LocalWriterConfig(
>             _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
>             enable=True,
>             stats_to_track=(
>                 <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
>                 <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
>                 <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
>                 <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
>                 <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
>                 <EventName.ETA: 'ETA (time)'>
>             ),
>             max_log_size=10
>         ),
>         profiler='basic'
>     ),
>     viewer=ViewerConfig(
>         relative_log_filename='viewer_log_filename.txt',
>         websocket_port=None,
>         websocket_port_default=7007,
>         websocket_host='0.0.0.0',
>         num_rays_per_chunk=32768,
>         max_num_display_images=512,
>         quit_on_train_completion=False,
>         image_format='jpeg',
>         jpeg_quality=90
>     ),
>     pipeline=VanillaPipelineConfig(
>         _target=<class 'tetranerf.nerfstudio.pipeline.TetrahedraNerfPipeline'>,
>         datamanager=VanillaDataManagerConfig(
>             _target=<class 'nerfstudio.data.datamanagers.base_datamanager.VanillaDataManager'>,
>             data=None,
>             camera_optimizer=CameraOptimizerConfig(
>                 _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
>                 mode='off',
>                 position_noise_std=0.0,
>                 orientation_noise_std=0.0,
>                 optimizer=AdamOptimizerConfig(
>                     _target=<class 'torch.optim.adam.Adam'>,
>                     lr=0.0006,
>                     eps=1e-15,
>                     max_norm=None,
>                     weight_decay=0
>                 ),
>                 scheduler=ExponentialDecaySchedulerConfig(
>                     _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
>                     lr_pre_warmup=1e-08,
>                     lr_final=None,
>                     warmup_steps=0,
>                     max_steps=10000,
>                     ramp='cosine'
>                 ),
>                 param_group='camera_opt'
>             ),
>             dataparser=MinimalDataParserConfig(
>                 _target=<class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParser'>,
>                 data=PosixPath('/home/nikhil/nerfstudio-main/tests/data/lego_test/minimal_parser')
>             ),
>             train_num_rays_per_batch=4096,
>             train_num_images_to_sample_from=-1,
>             train_num_times_to_repeat_images=-1,
>             eval_num_rays_per_batch=4096,
>             eval_num_images_to_sample_from=-1,
>             eval_num_times_to_repeat_images=-1,
>             eval_image_indices=(0,),
>             collate_fn=<function nerfstudio_collate at 0x7ff6f8c39480>,
>             camera_res_scale_factor=1.0,
>             patch_size=1
>         ),
>         model=TetrahedraNerfConfig(
>             _target=<class 'tetranerf.nerfstudio.model.TetrahedraNerf'>,
>             enable_collider=True,
>             collider_params={'near_plane': 2.0, 'far_plane': 6.0},
>             loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
>             eval_num_rays_per_chunk=4096,
>             tetrahedra_path=None,
>             num_tetrahedra_vertices=None,
>             num_tetrahedra_cells=None,
>             max_intersected_triangles=512,
>             num_samples=128,
>             num_fine_samples=128,
>             use_biased_sampler=True,
>             field_dim=64,
>             num_color_layers=1,
>             num_density_layers=3,
>             hidden_size=128,
>             input_fourier_frequencies=0,
>             initialize_colors=True,
>             use_gradient_scaling=True
>         )
>     ),
>     optimizers={
>         'fields': {
>             'optimizer': RAdamOptimizerConfig(
>                 _target=<class 'torch.optim.radam.RAdam'>,
>                 lr=0.001,
>                 eps=1e-08,
>                 max_norm=None,
>                 weight_decay=0
>             ),
>             'scheduler': ExponentialDecaySchedulerConfig(
>                 _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
>                 lr_pre_warmup=1e-08,
>                 lr_final=0.0001,
>                 warmup_steps=0,
>                 max_steps=300000,
>                 ramp='cosine'
>             )
>         }
>     },
>     vis='wandb',
>     data=None,
>     relative_model_dir=PosixPath('nerfstudio_models'),
>     steps_per_save=25000,
>     steps_per_eval_batch=1000,
>     steps_per_eval_image=2000,
>     steps_per_eval_all_images=50000,
>     max_num_iterations=300000,
>     mixed_precision=False,
>     use_grad_scaler=False,
>     save_only_latest_checkpoint=True,
>     load_dir=None,
>     load_step=None,
>     load_config=None,
>     load_checkpoint=None,
>     log_gradients=False
> )
> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> [21:47:03] Saving config to: outputs/unnamed/tetra-nerf/2023-06-01_214703/config.yml            experiment_config.py:128
>            Saving checkpoints to: outputs/unnamed/tetra-nerf/2023-06-01_214703/nerfstudio_models          trainer.py:136
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /home/kaito/miniforge3/envs/pytorch/bin/ns-train:8 in <module>                                   │
> │                                                                                                  │
> │   5 from nerfstudio.scripts.train import entrypoint                                              │
> │   6 if __name__ == '__main__':                                                                   │
> │   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
> │ ❱ 8 │   sys.exit(entrypoint())                                                                   │
> │   9                                                                                              │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:260 │
> │ in entrypoint                                                                                    │
> │                                                                                                  │
> │   257 │   """Entrypoint for use with pyproject scripts."""                                       │
> │   258 │   # Choose a base configuration and override values.                                     │
> │   259 │   tyro.extras.set_accent_color("bright_yellow")                                          │
> │ ❱ 260 │   main(                                                                                  │
> │   261 │   │   tyro.cli(                                                                          │
> │   262 │   │   │   AnnotatedBaseConfigUnion,                                                      │
> │   263 │   │   │   description=convert_markup_to_ansi(__doc__),                                   │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:246 │
> │ in main                                                                                          │
> │                                                                                                  │
> │   243 │   config.print_to_terminal()                                                             │
> │   244 │   config.save_config()                                                                   │
> │   245 │                                                                                          │
> │ ❱ 246 │   launch(                                                                                │
> │   247 │   │   main_func=train_loop,                                                              │
> │   248 │   │   num_gpus_per_machine=config.machine.num_gpus,                                      │
> │   249 │   │   num_machines=config.machine.num_machines,                                          │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:185 │
> │ in launch                                                                                        │
> │                                                                                                  │
> │   182 │   │   # world_size=0 uses one CPU in one process.                                        │
> │   183 │   │   # world_size=1 uses one GPU in one process.                                        │
> │   184 │   │   try:                                                                               │
> │ ❱ 185 │   │   │   main_func(local_rank=0, world_size=world_size, config=config)                  │
> │   186 │   │   except KeyboardInterrupt:                                                          │
> │   187 │   │   │   # print the stack trace                                                        │
> │   188 │   │   │   CONSOLE.print(traceback.format_exc())                                          │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/scripts/train.py:99  │
> │ in train_loop                                                                                    │
> │                                                                                                  │
> │    96 │   """                                                                                    │
> │    97 │   _set_random_seed(config.machine.seed + global_rank)                                    │
> │    98 │   trainer = config.setup(local_rank=local_rank, world_size=world_size)                   │
> │ ❱  99 │   trainer.setup()                                                                        │
> │   100 │   trainer.train()                                                                        │
> │   101                                                                                            │
> │   102                                                                                            │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/engine/trainer.py:14 │
> │ 9 in setup                                                                                       │
> │                                                                                                  │
> │   146 │   │   │   │   'test': loads train/test datasets into memory                              │
> │   147 │   │   │   │   'inference': does not load any dataset into memory                         │
> │   148 │   │   """                                                                                │
> │ ❱ 149 │   │   self.pipeline = self.config.pipeline.setup(                                        │
> │   150 │   │   │   device=self.device, test_mode=test_mode, world_size=self.world_size, local_r   │
> │   151 │   │   )                                                                                  │
> │   152 │   │   self.optimizers = self.setup_optimizers()                                          │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/configs/base_config. │
> │ py:57 in setup                                                                                   │
> │                                                                                                  │
> │    54 │                                                                                          │
> │    55 │   def setup(self, **kwargs) -> Any:                                                      │
> │    56 │   │   """Returns the instantiated object using the config."""                            │
> │ ❱  57 │   │   return self._target(self, **kwargs)                                                │
> │    58                                                                                            │
> │    59                                                                                            │
> │    60 # Machine related configs                                                                  │
> │                                                                                                  │
> │ /home/kaito/tetra-nerf/tetranerf/nerfstudio/pipeline.py:27 in __init__                           │
> │                                                                                                  │
> │   24 │   │   Pipeline.__init__(self)                                                             │
> │   25 │   │   self.config = config                                                                │
> │   26 │   │   self.test_mode = test_mode                                                          │
> │ ❱ 27 │   │   self.datamanager: VanillaDataManager = config.datamanager.setup(                    │
> │   28 │   │   │   device=device,                                                                  │
> │   29 │   │   │   test_mode=test_mode,                                                            │
> │   30 │   │   │   world_size=world_size,                                                          │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/configs/base_config. │
> │ py:57 in setup                                                                                   │
> │                                                                                                  │
> │    54 │                                                                                          │
> │    55 │   def setup(self, **kwargs) -> Any:                                                      │
> │    56 │   │   """Returns the instantiated object using the config."""                            │
> │ ❱  57 │   │   return self._target(self, **kwargs)                                                │
> │    58                                                                                            │
> │    59                                                                                            │
> │    60 # Machine related configs                                                                  │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/data/datamanagers/ba │
> │ se_datamanager.py:384 in __init__                                                                │
> │                                                                                                  │
> │   381 │   │   │   self.config.data = self.config.dataparser.data                                 │
> │   382 │   │   self.dataparser = self.dataparser_config.setup()                                   │
> │   383 │   │   self.includes_time = self.dataparser.includes_time                                 │
> │ ❱ 384 │   │   self.train_dataparser_outputs = self.dataparser.get_dataparser_outputs(split="tr   │
> │   385 │   │                                                                                      │
> │   386 │   │   self.train_dataset = self.create_train_dataset()                                   │
> │   387 │   │   self.eval_dataset = self.create_eval_dataset()                                     │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/data/dataparsers/bas │
> │ e_dataparser.py:163 in get_dataparser_outputs                                                    │
> │                                                                                                  │
> │   160 │   │   Returns:                                                                           │
> │   161 │   │   │   DataparserOutputs containing data for the specified dataset and split          │
> │   162 │   │   """                                                                                │
> │ ❱ 163 │   │   dataparser_outputs = self._generate_dataparser_outputs(split)                      │
> │   164 │   │   return dataparser_outputs                                                          │
> │   165                                                                                            │
> │   166                                                                                            │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/nerfstudio/data/dataparsers/min │
> │ imal_dataparser.py:53 in _generate_dataparser_outputs                                            │
> │                                                                                                  │
> │    50 │                                                                                          │
> │    51 │   def _generate_dataparser_outputs(self, split="train"):                                 │
> │    52 │   │   filepath = self.config.data / f"{split}.npz"                                       │
> │ ❱  53 │   │   data = np.load(filepath, allow_pickle=True)                                        │
> │    54 │   │                                                                                      │
> │    55 │   │   image_filenames = [filepath.parent / path for path in data["image_filenames"].to   │
> │    56 │   │   mask_filenames = None                                                              │
> │                                                                                                  │
> │ /home/kaito/miniforge3/envs/pytorch/lib/python3.10/site-packages/numpy/lib/npyio.py:405 in load  │
> │                                                                                                  │
> │    402 │   │   │   fid = file                                                                    │
> │    403 │   │   │   own_fid = False                                                               │
> │    404 │   │   else:                                                                             │
> │ ❱  405 │   │   │   fid = stack.enter_context(open(os_fspath(file), "rb"))                        │
> │    406 │   │   │   own_fid = True                                                                │
> │    407 │   │                                                                                     │
> │    408 │   │   # Code to distinguish from NumPy binary files and pickles.                        │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> FileNotFoundError: [Errno 2] No such file or directory:
> '/home/nikhil/nerfstudio-main/tests/data/lego_test/minimal_parser/train.npz'
> ```

Did you solve your issue train.npz not found? I am facing same issue.
