### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by weizizhuang** [jkulhanek/tetra-nerf#13]
Great work! May I ask some questions:
1. Can tetra-nerf be used in unbounded scenes? such as the Playground/Train (T&T) with large area of sky. And what should I pay attention to when I try tetra-nerf on my own data (most are unbounded scenes)?
2. I have tried the amazing online demos, so are these demos rendered real-time by the NeRF network?  And will you share the html codes so I can build one using my own data in the future?

**Comment by jkulhanek** [comment]
Hi, sorry for the delay.
1. It should be well-suitable for unbounded scenes (although adding a background model would help it greatly). You should pay attention to having good camera positions. Currently, it seems a bit sensitive to errors in camera positions.
2. Sorry, but the demos are not rendered in real-time. But you can download the trained model and launch the ns-viewer - it should be interactive enough on a lower res. In the demo a 360 video orbiting the scene is downloaded, locally decoded, and the images are then shown. The HTML codes are public in the "docs" branch of this repo. Let me know if you experience any problems!

**Comment by weizizhuang** [comment]
Thank you for kindly response, it's really useful.
