### ISSUE TITLE
ns-train Tetra-NeRF giving error

### ISSUE THREAD

**Issue by minar09** [jkulhanek/tetra-nerf#15]
Hi, I installed tetra-nerf again and everything went great. Built the package and produced point-cloud and tetrahedra successfully. But, the training command is having the below error now:  `TypeError: __init__() got an unexpected keyword argument 'grad_scaler'`. Can you please help? Thank you.

**Comment by jkulhanek** [comment]
Same issue here: https://github.com/nerfstudio-project/nerfstudio/issues/2012 ...Nerfstudio introduced a breaking change in the newer version. I will fix it.

**Comment by jkulhanek** [comment]
Can you please try if you are still experiencing the error?

**Comment by minar09** [comment]
Cool! Training now smoothly. Thank you very much for your quick help. Really appreciate it.
