### ISSUE TITLE
ns-train: error:  invalid choice: tetra-nerf

### ISSUE THREAD

**Issue by Mehi44** [jkulhanek/tetra-nerf#19]
Hello,

My nerf studio version is 0.2.2 which is higher than the one required 0.2.0. But it seems not to have tetra-nerf implemented. Is there some sort of path variable that needs to be introduced somewhere or something?

```
(nerfstudio) mehi@DGX3:/nas1/mehi/tetranerf$ ns-train tetra-nerf-original --pipeline.model.tetrahedra-path /nas1/mehi/tetranerf/data/sparse.th minimal-parse
r --data /nas1/mehi/tetranerf/data
usage: ns-train [-h]
                {nerfacto,nerfacto-big,depth-nerfacto,volinga,instant-ngp,instant-ngp-bounded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,dnerf,phototouri
sm,nerfplayer-nerfacto,nerfplayer-ngp,neus,neus-facto}

 
ns-train: error: argument {nerfacto,nerfacto-big,depth-nerfacto,volinga,instant-ngp,instant-ngp-bounded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,dnerf,phototourism,nerfplayer-nerfacto,nerfplayer-ngp,neus,neus-facto}: invalid choice: 'tetra-nerf-original' (choose from 'nerfacto', 'nerfacto-big', 'depth-nerfacto', 'volinga', 'instant-ngp', 'instant-ngp-bounded', 'mipnerf', 'semantic-nerfw', 'vanilla-nerf', 'tensorf', 'dnerf', 'phototourism', 'nerfplayer-nerfacto', 'nerfplayer-ngp', 'neus', 'neus-facto')
```

**Comment by liuxiaozhu01** [comment]
From what I've experienced, tetra-nerf should be installed firstly. 
Try to run `cmake . && make`. If everything goes well, the .so extension will exist in tetranerf/utils/extension
Then you can install it by `pip install .` After that, `ns-train` may work well with tetranerf :)

**Comment by Mehi44** [comment]
I have already installed tetra-nerf with cmake, I ran the commands 
```
python -m tetranerf.scripts.process_images --path /nas1/mehi/tetranerf/data
python -m tetranerf.scripts.triangulate --pointcloud /nas1/mehi/tetranerf/data/sparse.ply --output /nas1/mehi/tetranerf/data/sparse.th
```
successfully 
but ns-train doesnt work 

I tried what you said and I got this  :
```
(nerfstudio) mehi@DGX3:/nas1/mehi/tetranerf/tetra-nerf/tetranerf/utils/extension$ pip install .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

the extensions folder doesnt have a setup.py in it 

```
(nerfstudio) mehi@DGX3:/nas1/mehi/tetranerf/tetra-nerf/tetranerf/utils/extension$ ls
__init__.py  __pycache__  tetranerf_cpp_extension.cpython-39-x86_64-linux-gnu.so
```

**Comment by liuxiaozhu01** [comment]
sorry that i dont make it clear.
the cmd `pip install .` should be executed at directory `tetra-nerf` where `setup.py` is located

**Comment by Mehi44** [comment]
It's solved as follows : 

I downgraded to nerfstudio 0.2.0
I reinstalled tetra-nerf with cmake . && make
then I ran pip install .
finally added PYTHONPATH variable pointing to the tetra-nerf location
