### ISSUE TITLE
Extract the tetra-hedra field as a mesh.

### ISSUE THREAD

**Issue by Mehi44** [jkulhanek/tetra-nerf#20]
Hello,

I am trying to extract the tetra-hedra field as a mesh. I assume its the one found in the sparse.th file which I loaded like this :
```
import torch
tetra = torch.load('/nas1/mehi/tetranerf/data/sparse.th')
```

```
{'cells': tensor([[ 38157,  38158,  66460,  54392],
         [105163,  49299,  74371, 105174],
         [ 47005,  61892,  43594,  11389],
         ...,
         [ 29310,  67025,  79496, 147919],
         [ 79496,  59916,  29310, 147919],
         [ 59916,  79496,  67025, 147919]], dtype=torch.int32),
 'vertices': tensor([[ 3.0021,  1.6830, -1.4865],
         [-0.9175,  0.5457, -0.0196],
         [ 1.7000, -0.2302,  4.2775],
         ...,
         [-0.4964,  1.3246, -3.3205],
         [-2.6612,  0.9261, -0.3657],
         [-1.9667,  0.8272, -2.4944]]),
 'colors': tensor([[ 38,  36,  36, 255],
         [207, 189, 157, 255],
         [ 67,  67,  70, 255],
         ...,
         [173, 168, 167, 255],
         [ 42,  29,  29, 255],
         [161, 157, 153, 255]], dtype=torch.uint8)}
```

Is there a way to export a mesh or to turn this into a mesh that can be visualized in MeshLab or something ?

**Comment by jkulhanek** [comment]
Hi,

You can use the following code:
```
tetrahedra_data = torch.load(tetrahedra)
    faces = torch.cat((
        torch.roll(tetrahedra_data["cells"], -1, -1),
        torch.roll(tetrahedra_data["cells"], -2, -1),
        torch.roll(tetrahedra_data["cells"], -3, -1),
        torch.roll(tetrahedra_data["cells"], -4, -1),
    ), 0)
    vertices = tetrahedra_data["vertices"]
    trimesh.Trimesh(
        vertices.numpy(),
        faces.numpy(),
        vertex_colors=tetrahedra_data["colors"].numpy(),
    ).export(output)
```

**Comment by Mehi44** [comment]
Much thanks, 

This seems to work. It also gives some results that are awkward to visualize, but I assume this is due to the properties of the Delaunay triangulation described in the paper.

some of the results look like this as visualized by Cloud Compare :
sparse point cloud
![cloud1](https://github.com/jkulhanek/tetra-nerf/assets/118313489/6168e7e4-27c2-4021-a062-4d3497ed9e26)

corresponding mesh from the same perspective
![mesh1](https://github.com/jkulhanek/tetra-nerf/assets/118313489/fd47c91a-fca8-4009-b0f0-52944b48ab02)


sparse point cloud
![cloud2](https://github.com/jkulhanek/tetra-nerf/assets/118313489/cb070ad4-b2b8-4ec9-aad7-6c9cb4f349d5)
corresponding mesh from the same perspective
![mesh2](https://github.com/jkulhanek/tetra-nerf/assets/118313489/d50863e5-32ea-4ff6-9f44-cb45beb9cc17)

**Comment by jkulhanek** [comment]
It is not a surface mesh but rather a triangle soup consisting of all faces of all tetrahedra. TetraNeRF is rendering this representation volumetrically (most triangles will be transparent), but you are visualizing the surface of this object. I recommend rendering it as a wireframe.

**Comment by Mehi44** [comment]
Thanks! This looks quite interesting. I think it's correct to assume that the more dense the input point cloud the more the rendered surfaces are more accurate and true to life?

![mesh-wire1](https://github.com/jkulhanek/tetra-nerf/assets/118313489/a31382a5-f3e3-4f5d-9bb9-5c91b500d8b7)
![wire1](https://github.com/jkulhanek/tetra-nerf/assets/118313489/74c933a8-391c-4f2d-a401-10a060d420ad)
