### ISSUE TITLE
Using dense point cloud

### ISSUE THREAD

**Issue by Mehi44** [jkulhanek/tetra-nerf#21]
In the original paper it stated that the tetra-hedra field can be obtained from the sparse or dense point cloud. 
How can we use the dense point cloud ?

**Comment by jkulhanek** [comment]
Please take a look at any `tetranerf/scripts/process_*`. There should be a `--run-dense` flag which enables the dense PC reconstruction.

**Comment by Mehi44** [comment]
That seems to do it, thanks! 
also must change the path here 
`python -m tetranerf.scripts.triangulate --pointcloud <data folder>/dense.ply --output <data folder>/dense.th`
