### ISSUE TITLE
How to debug in Pycharm professional

### ISSUE THREAD

**Issue by 2668342956** [jkulhanek/tetra-nerf#24]
Hi, thanks for your great job of tetra-nerf, I have trouble when I try to debug the code in pycharm.
As your command for training is, for example, "ns-train tetra-nerf-original --pipeline.model.tetrahedra-path data/blender/lego/pointnerf-0.5.th blender-data --data data/blender/lego", then how can I debug the code in the pycharm, which file should I start with?  I'm confused how to fill in the field of  scripts.
Thanks again for your great work and my debug configuration are like this.

**Comment by 2668342956** [comment]
![2f93ac93e28c42353ad1a08e2435c92](https://github.com/jkulhanek/tetra-nerf/assets/77038542/9c07771a-0238-49b8-bd83-ff77344750f2)

**Comment by jkulhanek** [comment]
Hi, I am not familiar with PyCharm, but perhaps you want to point it to nerfstudio/scripts/train.py?

**Comment by 2668342956** [comment]
oh, thanks a lot for your reply, I find it. By the way, I am a beginner in this field,  so I wanna konw how the excellent researcher ,like you, will test and debug the code. If it's not in pycharm, is it in vscode or others.

**Comment by jkulhanek** [comment]
I use either vscode or vim. To debug python I would just put breakpoint() call in the code. Were you asking about debugging the cpp extension?

**Comment by 2668342956** [comment]
oh, I get it. I just wanted to know the software you familar with. Thanks again, looking forwad to your better works in the future!
