### ISSUE TITLE
error when running in docker

### ISSUE THREAD

**Issue by XuqianRen** [jkulhanek/tetra-nerf#25]
Hi, when I try to run ns-train -h in docker, I got this problem:
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 16 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 17 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 18 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 19 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 20 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 21 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 22 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 23 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 24 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 25 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 26 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 27 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 28 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 29 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 30 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 32: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/home/user/nerfstudio/nerfstudio/scripts/train.py", line 54, in <module>
    import numpy as np
  File "/home/user/.local/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/home/user/.local/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/user/.local/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/user/.local/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt

seems I lack some permission to access. May I ask how I can solve this problem? Thanks.

**Comment by jkulhanek** [comment]
This is a very weird issue. Can you check if you can run vanilla nerfstudio from the official docker image?

**Comment by XuqianRen** [comment]
Seems also can't :( I met this error:
  File "/home/user/.local/bin/ns-install-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/completions/install.py", line 282, in entrypoint
    tyro.cli(main, description=__doc__)
  File "/home/user/.local/lib/python3.10/site-packages/tyro/_cli.py", line 124, in cli
    _cli_impl(
  File "/home/user/.local/lib/python3.10/site-packages/tyro/_cli.py", line 327, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/user/.local/lib/python3.10/site-packages/tyro/_calling.py", line 188, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/home/user/nerfstudio/scripts/completions/install.py", line 250, in main
    with CONSOLE.status("[bold]:writing_hand:  Generating completions...", spinner="bouncingBall"):
  File "/home/user/.local/lib/python3.10/site-packages/rich/status.py", line 97, in __enter__
    self.start()
  File "/home/user/.local/lib/python3.10/site-packages/rich/status.py", line 87, in start
    self._live.start()
  File "/home/user/.local/lib/python3.10/site-packages/rich/live.py", line 132, in start
    self._refresh_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by XuqianRen** [comment]
When I try to use install tetra-nerf in my environment, I got this error: cmake . is ok but when trying "make" it reports the following error  @jkulhanek 

:
/home/nvme/kqxure/code/nerfstudio/tetra-nerf/src/tetrahedra_tracer.cpp:86:30: error: ‘setw’ is not a member of ‘std’
     std::cerr << "[" << std::setw(2) << level << "][" << std::setw(12) << tag << "]: "
                              ^~~~
/home/nvme/kqxure/code/nerfstudio/tetra-nerf/src/tetrahedra_tracer.cpp:86:30: note: suggested alternative: ‘get’
     std::cerr << "[" << std::setw(2) << level << "][" << std::setw(12) << tag << "]: "
                              ^~~~
                              get
/home/nvme/kqxure/code/nerfstudio/tetra-nerf/src/tetrahedra_tracer.cpp:86:63: error: ‘setw’ is not a member of ‘std’
     std::cerr << "[" << std::setw(2) << level << "][" << std::setw(12) << tag << "]: "
                                                               ^~~~
/home/nvme/kqxure/code/nerfstudio/tetra-nerf/src/tetrahedra_tracer.cpp:86:63: note: suggested alternative: ‘get’
     std::cerr << "[" << std::setw(2) << level << "][" << std::setw(12) << tag << "]: "
                                                               ^~~~
                                                               get
make[2]: *** [CMakeFiles/tetranerf_cpp_extension.dir/build.make:628: CMakeFiles/tetranerf_cpp_extension.dir/src/tetrahedra_tracer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/tetranerf_cpp_extension.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by jkulhanek** [comment]
What are your gcc, cuda, optix, and cmake versions?

**Comment by XuqianRen** [comment]
gcc 8.4
nvcc --version 11.8
optix 7.5
cmake 3.26

**Comment by jkulhanek** [comment]
Can you try with gcc 11?

**Comment by XuqianRen** [comment]
I tried gcc 11 but got another problem, so I further tried gcc 10, gcc 9 and found gcc 9 works. Now I can run the repo. Thanks :D
