### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by balogistvan** [jkulhanek/tetra-nerf#6]
I have a problem, when i try build the tetra-nerf.  Can you help me, what is the problem. My nerfstudio is working well. Thank you.

File "C:\Users\balog\AppData\Local\Temp\pip-req-build-k9jha4ep\setup.py", line 107, in build_extension
          subprocess.run(["cmake", ext.sourcedir, *cmake_args], cwd=ext.sourcedir, check=True)
        File "C:\Users\balog\anaconda3\envs\nerfstudio\lib\subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\balog\\AppData\\Local\\Temp\\pip-req-build-k9jha4ep', '-DPYTHON_EXECUTABLE=C:\\Users\\balog\\anaconda3\\envs\\nerfstudio\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DEXAMPLE_VERSION_INFO=0.1.1']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tetra-nerf
  Running setup.py clean for tetra-nerf
Failed to build tetra-nerf
ERROR: Could not build wheels for tetra-nerf, which is required to install pyproject.toml-based projects

**Comment by jkulhanek** [comment]
Sorry, only linux is supported for now. On windows I recommend using the docker (dockerfile in the repository).
