### ISSUE TITLE
Show training progress of tetra-nerf like nerfacto not no wandb

### ISSUE THREAD

**Issue by tkclimb** [jkulhanek/tetra-nerf#8]
I recently started to use this brilliant project, and I'm looking for the way to see the training progress with visualization like `nerfacto` on nerfstudio.
Is it possible to visualize tetra-nerf rendering result during `ns-train` by viewer.nerf.studio?

**Comment by jkulhanek** [comment]
Hi, thanks!
It should be possible.
Just specify `--vis viewer` flag to enable.
You can explore the trained checkpoints first by using `ns-viewer  --load-config ...path-to-downloaded-checkpoint..."

**Comment by tkclimb** [comment]
I tried that way, but the `vis` flag seems not to be supported with tetra-nerf. I pasted the error message below. point cloud data `pointnerfj-0.5.th` was made from the one point-nerf provided.

```
ns-train tetra-nerf --pipeline.model.tetrahedra-path data/blender/lego/pointnerf-0.5.th blender-data --data /data/nerf_synthetic/lego --vis viewer
usage: ns-train [-h]
                {nerfacto,nerfacto-big,depth-nerfacto,volinga,instant-ngp,instant-ngp-bounded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,dnerf,phototourism,nerfplayer-nerfacto,nerfplayer-ngp,neus,neus-
facto,tetra-nerf,tetra-nerf-original}
 
ns-train: error: unrecognized arguments: --vis viewer
```

**Comment by jkulhanek** [comment]
The vis flag has to be added before blender-data.

**Comment by jkulhanek** [comment]
Please reopen if it doesn't work.
