### ISSUE TITLE
No Qt platform plugin could be initialized - Docker

### ISSUE THREAD

**Issue by Lycophyta** [jkulhanek/tetra-nerf#9]
I am following the instructions under 'Reproducing Results' in a docker container.

`$ python -m tetranerf.scripts.process_blender --transforms /data/blender/ficus/transforms_train.json --output /data/blender/ficus
Images copied to /tmp/tmp7q1swz2m/images
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

*** Aborted at 1684267602 (unix time) try "date -d @1684267602" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800000056) received by PID 86 (TID 0x7fd2539ae080) from PID 86; stack trace: ***
    @     0x7fd259557046 (unknown)
    @     0x7fd257801520 (unknown)
    @     0x7fd257855a7c pthread_kill
    @     0x7fd257801476 raise
    @     0x7fd2577e77f3 abort
    @     0x7fd257df4ba3 QMessageLogger::fatal()
    @     0x7fd2583fb713 QGuiApplicationPrivate::createPlatformIntegration()
    @     0x7fd2583fbc08 QGuiApplicationPrivate::createEventDispatcher()
    @     0x7fd258024b17 QCoreApplicationPrivate::init()
    @     0x7fd2583feb70 QGuiApplicationPrivate::init()
    @     0x7fd258b12ced QApplicationPrivate::init()
    @     0x55bd3e2363dd colmap::RunFeatureExtractor()
    @     0x55bd3e228499 main
    @     0x7fd2577e8d90 (unknown)
    @     0x7fd2577e8e40 __libc_start_main
    @     0x55bd3e22b3e5 _start
──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: ['colmap', 'feature_extractor', '--database_path', 
PosixPath('/data/blender/ficus/sparse/database.db'), '--image_path', PosixPath('/tmp/tmp7q1swz2m/images'), 
'--ImageReader.single_camera', '1', '--ImageReader.camera_model', 'SIMPLE_PINHOLE', '--ImageReader.camera_params', 
'1111.1110311937682,400.0,400.0']
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────`

**Comment by jkulhanek** [comment]
I will look into it. This is related:
 https://github.com/NVlabs/instant-ngp/discussions/300
 https://github.com/NVlabs/instant-ngp/issues/329
 https://github.com/nerfstudio-project/nerfstudio/issues/524

**Comment by jkulhanek** [comment]
I am building a new image with COLMAP built from source.  I hope it will resolve the issue.

**Comment by jkulhanek** [comment]
Ok, I have updated the dockerfile and the image. Can you please test it now?

**Comment by Lycophyta** [comment]
The latest image has resolved the issue! Thank you very much for all that you have done :)
